export const columns = [
  {
    field: "batchNumber",
    header: "Batch Number",
    render: (item) => <span>{`${item?.batchNo ?? ""}`}</span>,
  },
  {
    field: "certificationsStatus",
    header: "Certification status",
    render: (item) => <span>{item?.cws?.name ?? "N/A"}</span>,
  },
  {
    field: "Qauntity",
    header: "Parchment Qty(kg)",
    render: (item) => (
      <span>{(item?.outputKgs?.N1 ?? 0) + (item?.outputKgs?.N2 ?? 0)}</span>
    ),
  },
  { field: "Cumulative", header: "Cumulative (Kg)" },
  { field: "driverPhone", header: "Date of analysis" },
  { field: "driverPhone", header: "MoistureContentlag(%)/Samples" },
  { field: "driverPhone", header: "Moisture Content CWS (%)/Delivery" },
  { field: "driverPhone", header: "Variation M.C" },
  { field: "driverPhone", header: "16+" },
  { field: "driverPhone", header: "15.00" },
  { field: "driverPhone", header: "Aver.15+/Delivery" },
  { field: "driverPhone", header: "AV.15+ Samples" },
  { field: "driverPhone", header: "Variation 15+" },
  { field: "driverPhone", header: "14.00" },
  { field: "driverPhone", header: "13.00" },
  { field: "driverPhone", header: "Aver. 13/14/Delivery" },
  { field: "driverPhone", header: "Av.13/14 Samples" },
  { field: "driverPhone", header: "Variation 13/14" },
  { field: "driverPhone", header: "B13" },
  { field: "driverPhone", header: "Defects (%)" },
  { field: "driverPhone", header: "Aver.LG/Delivery" },
  { field: "driverPhone", header: "AV.LG Samples" },
  { field: "driverPhone", header: "Variation LG" },
  { field: "driverPhone", header: "OT Delivery (%)" },
  { field: "driverPhone", header: "O.T/Samples" },
  { field: "driverPhone", header: "Flovor/After taste" },
  { field: "driverPhone", header: "Acidity" },
  { field: "driverPhone", header: "Body" },
  { field: "driverPhone", header: "Comments" },
  { field: "driverPhone", header: "Potato cups (%)" },
  { field: "driverPhone", header: "PP Score/Delivery" },
  { field: "driverPhone", header: "PP Score/samples" },
  { field: "driverPhone", header: "Category" },
  { field: "driverPhone", header: "Variation PP Score" },
  { field: "driverPhone", header: "Sample storage" },
  { field: "driverPhone", header: "" },
];
