export const columns = [
  {
    field: "#",
    header: "#",
  },
  {
    field: "batchNumber",
    header: "Batch Number",
  },

  // {
  //   field: "Qauntity",
  //   header: "Parchment Qty(kg)",
  // },
  // { field: "driverPhone", header: "Date of analysis" },
  { field: "driverPhone", header: "Transported (kg)" },
  { field: "driverPhone", header: "Received Category (kg)" },
  { field: "driverPhone", header: "Variation (kg)" },
  { field: "driverPhone", header: "16+" },
  { field: "driverPhone", header: "15.00" },
  { field: "driverPhone", header: "AV.15+/Delivery" },
  { field: "driverPhone", header: "AV.15+ Samples" },
  { field: "driverPhone", header: "Variation 15+" },
  { field: "driverPhone", header: "14.00" },
  { field: "driverPhone", header: "13.00" },
  { field: "driverPhone", header: "AV.13/14/Delivery" },
  { field: "driverPhone", header: "AV.13/14 Samples" },
  { field: "driverPhone", header: "Variation 13/14" },
  { field: "driverPhone", header: "B12" },
  { field: "driverPhone", header: "Defects (%)" },
  { field: "driverPhone", header: "AV.LG/Delivery" },
  { field: "driverPhone", header: "AV.LG Samples" },
  { field: "driverPhone", header: "Variation LG" },
  { field: "driverPhone", header: "OT Delivery (%)" },
  { field: "driverPhone", header: "O.T/Samples" },
  { field: "driverPhone", header: "Variation OT" },
  { field: "driverPhone", header: "PP Score/Delivery" },
  { field: "driverPhone", header: "PP Score/samples" },
  { field: "driverPhone", header: "Variation PP Score" },
  { field: "driverPhone", header: "Sample storage" },
  { field: "driverPhone", header: "Car Plat" },
];
